spring:
  datasource:
    url: jdbc:mysql://192.168.113.15:3306/uploadfile?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 3nodapp
  jpa:
    show-sql: true
  mvc:
    view:
      prefix: /templates/
      suffix: .ftl
    static-path-pattern: /static/**
server:
  servlet:
    context-path: /bigfile
